Controllers/AccueilController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProjetRh.Models;
using Rh.Models;

namespace ProjetRH.Controllers;
public class AccueilController : Controller
{
    public IActionResult InsertionDemand()
    {
        return View("/Views/listEmploye");
    }
    public IActionResult EmployeListe(){
        // string idDept = Request.Query["idDept"];
        Connexion c = new Connexion();
        Employes emp = new Employes(); 
        Employes[] listemp = emp.GetDonnee(c);
        ViewBag.ListeEmp = listemp;
        return View();
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProjetRH.Models;

namespace ProjetRH.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
    public IActionResult Teste()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Bienvenue sur notre site";
}
<h1>@ViewData["Title"]</h1>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="styles.css">
        <div class="container">
            <a href="@Url.Action("EmployeListe", "Accueil")" class="view-button">Voir les employés</a>
            <a href="@Url.Action("insertionDemande", "EMploye")" class="view-button">Envoyer une nouvelle demande</a>
        </div> 
<style>

    .container {
    text-align: center;
    padding: 30px;  
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    background-color: #fff; /* Ajout d'un fond blanc pour un meilleur contraste */
    display: flex;
    justify-content: center;
}

h1 {
    font-size: 24px;
    margin-bottom: 20px;
}
.view-button{
    padding: 10px 20px;
    font-size: 16px;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
    margin: 0 10px;
    cursor: pointer;
}
a{
    text-decoration: none;
    color: #fff;
}

a:hover {
    background-color: #0056b3;
    color:#fff;
}

</style>

Views/Home/Teste.cshtml
<h1>huhu</h1>